### PR TITLE
Fixed the invalid json format

### PR DESCRIPTION
**Pull request by YasuhiroABE**
Hi, I've found an issue of invalid json format for usage data.
Please check this patch.

Thank you for your support.

### CODE REVIEW

**Comment by StoneStepsInc** [comment]
Thanks for the fixes. Will pull them all this weekend.

**Comment by StoneStepsInc** [comment]
Both changes are in, but I had to rebase this one, so the pull request isn't dismissed. I will release v6.2.1 from branch `v6-2` tomorrow.

**Comment by StoneStepsInc** [comment]
Closing this pull request. Both changes are in the 6.2.1 release binaries. If you are building from source, you may want to pull again to pick up the fix for JavaScript encoding erroneously used in JSON output.

Thanks for your help.

**Comment by YasuhiroABE** [comment]
OK.
Thank you for your support.

**Pull request closed without merging**
